/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExternalSearchRouteImport } from './routes/external-search'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MoviesIndexRouteImport } from './routes/movies.index'
import { Route as MoviesMovieIdRouteImport } from './routes/movies.$movieId'
import { Route as MoviesNewRouteImport } from './routes/movies.new'
import { Route as MoviesMovieIdEditRouteImport } from './routes/movies_.$movieId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalSearchRoute = ExternalSearchRouteImport.update({
  id: '/external-search',
  path: '/external-search',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MoviesRoute,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/$movieId',
  path: '/$movieId',
  getParentRoute: () => MoviesRoute,
} as any)
const MoviesNewRoute = MoviesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MoviesRoute,
} as any)
const MoviesMovieIdEditRoute = MoviesMovieIdEditRouteImport.update({
  id: '/movies_/$movieId/edit',
  path: '/movies/$movieId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/external-search': typeof ExternalSearchRoute
  '/movies': typeof MoviesRouteWithChildren
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/new': typeof MoviesNewRoute
  '/movies/': typeof MoviesIndexRoute
  '/movies/$movieId/edit': typeof MoviesMovieIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/external-search': typeof ExternalSearchRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/new': typeof MoviesNewRoute
  '/movies': typeof MoviesIndexRoute
  '/movies/$movieId/edit': typeof MoviesMovieIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/external-search': typeof ExternalSearchRoute
  '/movies': typeof MoviesRouteWithChildren
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/new': typeof MoviesNewRoute
  '/movies/': typeof MoviesIndexRoute
  '/movies_/$movieId/edit': typeof MoviesMovieIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/external-search'
    | '/movies'
    | '/movies/$movieId'
    | '/movies/new'
    | '/movies/'
    | '/movies/$movieId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/external-search'
    | '/movies/$movieId'
    | '/movies/new'
    | '/movies'
    | '/movies/$movieId/edit'
  id:
    | '__root__'
    | '/'
    | '/external-search'
    | '/movies'
    | '/movies/$movieId'
    | '/movies/new'
    | '/movies/'
    | '/movies_/$movieId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExternalSearchRoute: typeof ExternalSearchRoute
  MoviesRoute: typeof MoviesRouteWithChildren
  MoviesMovieIdEditRoute: typeof MoviesMovieIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external-search': {
      id: '/external-search'
      path: '/external-search'
      fullPath: '/external-search'
      preLoaderRoute: typeof ExternalSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof MoviesRoute
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof MoviesRoute
    }
    '/movies/new': {
      id: '/movies/new'
      path: '/new'
      fullPath: '/movies/new'
      preLoaderRoute: typeof MoviesNewRouteImport
      parentRoute: typeof MoviesRoute
    }
    '/movies_/$movieId/edit': {
      id: '/movies_/$movieId/edit'
      path: '/movies/$movieId/edit'
      fullPath: '/movies/$movieId/edit'
      preLoaderRoute: typeof MoviesMovieIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MoviesRouteChildren {
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  MoviesNewRoute: typeof MoviesNewRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
}

const MoviesRouteChildren: MoviesRouteChildren = {
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  MoviesNewRoute: MoviesNewRoute,
  MoviesIndexRoute: MoviesIndexRoute,
}

const MoviesRouteWithChildren =
  MoviesRoute._addFileChildren(MoviesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExternalSearchRoute: ExternalSearchRoute,
  MoviesRoute: MoviesRouteWithChildren,
  MoviesMovieIdEditRoute: MoviesMovieIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
